### ISSUE TITLE
Seems to have stopped working correctly after "Take screenshots #70"

### ISSUE THREAD

**Issue by MikeLister** [jtrim-ons/get-ons-vis-screenshots#1]
The most recent update to https://jtrim-ons.github.io/get-ons-vis-screenshots/ was on 2024-05-12. Seems to have stopped updating after this point.
The `Take screenshots` process seems to be working fine until #70, after that the process takes far longer (~24 minutes instead of ~1 minute)

**Comment by jtrim-ons** [comment]
Hi Mike! Thanks for letting me know. I knew it was bound to break sooner or later :-) I'll take a look.

**Comment by jtrim-ons** [comment]
It looks like the `/data` files now have a field called `"related_documents"` instead of `"relatedDocuments"`. Hopefully it's fixed now, but I'm not very confident! Let me know if it seems to have worked.

**Comment by jtrim-ons** [comment]
Hmmm... it's still quitting early on https://www.ons.gov.uk/releases/privaterentandhousepricesukjune2024/data because it sees that one of the related documents was published in March. It might take me a couple of weeks to have time to fix it properly.

**Comment by jtrim-ons** [comment]
Hopefully fixed now! Let me know if anything goes wrong again.

**Comment by MikeLister** [comment]
Thanks James - super helpful!
